name: aa_4step_inventory
description: "AA 4. Step Inventory app"
publish_to: 'none'

version: 1.0.1+21

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  csv: ^5.0.0
  flutter_file_dialog: ^3.0.2
  file_picker: ^10.3.3
  flutter_modular: ^6.3.4
  google_fonts: ^5.0.0
  googleapis_auth: ^1.4.1
  googleapis: ^11.4.0
  path_provider: ^2.1.1
  google_sign_in: ^5.4.2
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  analyzer: ^6.4.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/icon/icon.png"

  windows:
    generate: true
    image_path: "assets/icon/icon.png"

  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
